### ISSUE TITLE
Creating a project package in Trados Studio deletes DQF meta-data from .sdlproj file

### ISSUE THREAD

**Issue by achimr** [TAUSBV/dqf-api#23] opened 2015-05-29 18:04 UTC
Reported by Ryan: When creating a project package in Trados Studio, all DQF metadata is lost from the .sdlproj file. So when the PM sends a package to a translator, no data is returned to the DQF server as that translator works on the project.

**Comment by HenkBoxma** [comment] 2015-06-11 13:11
This one should be fixed now. Awating for conformation from Steve and Ryan (LDS Church)

**Comment by HenkBoxma** [comment] 2015-06-11 13:12
This is the same as issue  #35 for increment 1.0

**Comment by HenkBoxma** [comment] 2015-06-18 10:15
Fixed. Root cause is the update of Studio to a newer version. In that new version the metadata was set to the clone. For details, see https://community.sdl.com/developers/language-developers/f/58/p/4347/16149#16149

**Closed by HenkBoxma** 2015-06-18 10:15 UTC
Labels: trados plugin
